
[[configs]]
name = "config0"
learning_rate = 0.002
n_steps = 1024
batch_size = 64
n_epochs = 10
gamma = 0.99
gae_lambda = 0.95
clip_range = 0.2
ent_coef = 0.01
vf_coef = 0.5
max_grad_norm = 0.5

[[configs]]
name = "config1"
learning_rate = 0.0003
n_steps = 512
batch_size = 128
clip_range = 0.2
ent_coef = 0.01
vf_coef = 0.5

[[configs]]
name = "config2"
learning_rate = 0.0005
n_steps = 1024
batch_size = 256
clip_range = 0.2
ent_coef = 0.02
vf_coef = 0.5

[[configs]]
name = "config3"
learning_rate = 0.0001
n_steps = 2048
batch_size = 128
clip_range = 0.1
ent_coef = 0.01
vf_coef = 0.3
